# Generated by Django 5.0 on 2023-12-04 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('ContactId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=255)),
                ('LastName', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=254)),
                ('Phone', models.BigIntegerField()),
                ('Address', models.TextField()),
                ('Image', models.ImageField(blank=True, null=True, upload_to='contact_images/')),
            ],
            options={
                'db_table': 'contact',
            },
        ),
    ]
